# Generated by Django 5.0 on 2025-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('tour_type', models.CharField(choices=[('Romantic', 'Romantic'), ('Solo', 'Solo'), ('Family', 'Family'), ('Friends', 'Friends'), ('Business Trip', 'Business Trip'), ('Honeymoon', 'Honeymoon'), ('Adventure', 'Adventure')], max_length=50)),
                ('accommodation_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Apartment', 'Apartment'), ('Campsite', 'Campsite'), ('Guesthouse', 'Guesthouse')], max_length=50)),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
